import Head from 'next/head';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home(){
    const [quote, setQuote] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            const response = await fetch('https://zorcmspowc.execute-api.ap-northeast-2.amazonaws.com/prod/quote');
            const data = await response.json();
            setQuote(data);
            console.log(`Client-side rendered page: "${data.message}"`);
        }
        fetchData();
        
    }, []);

    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <div className={styles.card}>
                <h1>CSR</h1>
            </div>
            <div className={styles.center}>
                <div className={styles.description}>
                    { quote ? (
                            <p>{quote.message}</p>
                        ) : ( 
                            <p>Loading ...</p>
                        )
                    }
                </div>
            </div>
            <div>
                <a href="ssr">server-side rendered page 에서 보기</a>
            </div>
        </main>
        </>
    )
}

